name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Docker-Image-Scan:
    runs-on: ubuntu-latest
    name: Docker Image Scan
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Docker Build   
      run: |
        docker build -t go-api:${{ github.sha }} .
      
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@0.2.2
      with:
          image-ref: 'go-api:${{ github.sha }}'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
