name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Docker-Image-Scan:
    runs-on: ubuntu-latest
    name: Docker Image Scan
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Docker Build   
      run: |
        docker build -t go-crud:latest .
      
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@0.2.2
      with:
          image-ref: 'go-crud:latest'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

  Docker-Image-Push:
    if: ${{ always() }}
    needs: [Docker-Image-Scan]
    runs-on: ubuntu-latest
    name: Docker Image Push
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Docker Build   
      run: |
        docker build -t go-crud:latest .
        
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Log in to DO Container Registry 
      run: |
        doctl registry login --expiry-seconds 600
        docker tag go-crud:$(date +%s) registry.digitalocean.com/williamsquared/go-crud:latest        
        docker push registry.digitalocean.com/williamsquared/go-crud:latest
