name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Docker-Image-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t go-crud:$(date +%s) .
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.2.2
      with:
        scan-type: image
        image-ref: go-crud:$(date +%s)
        severity: HIGH,CRITICAL
